name: AVPLiDARMapper
options:
  bundleIdPrefix: com.smartpuppy
  deploymentTarget:
    visionOS: "2.0"
  createIntermediateGroups: true
  generateEmptyDirectories: true

settings:
  DEVELOPMENT_TEAM: "" # Add your team ID here
  PRODUCT_BUNDLE_IDENTIFIER: com.smartpuppy.avplidarmapper
  SWIFT_VERSION: 6.0
  TARGETED_DEVICE_FAMILY: 7 # Vision Pro

targets:
  AVPLiDARMapper:
    type: application
    platform: visionOS
    deploymentTarget: "2.0"
    sources:
      - path: LiDARMapper
        createIntermediateGroups: true
    settings:
      INFOPLIST_FILE: LiDARMapper/Info.plist
      PRODUCT_NAME: AVPLiDARMapper
      ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
      ENABLE_PREVIEWS: YES
      SWIFT_EMIT_LOC_STRINGS: YES
    capabilities:
      com.apple.developer.spatial-tracking.full: true
    info:
      path: LiDARMapper/Info.plist
      properties:
        UILaunchScreen: {}
        UIApplicationSceneManifest:
          UIApplicationSupportsMultipleScenes: true
          UIApplicationPreferredDefaultSceneSessionRole: UIWindowSceneSessionRoleImmersiveSpaceApplication
          UISceneConfigurations:
            UIWindowSceneSessionRoleApplication:
              - UISceneConfigurationName: Default Configuration
                UISceneDelegateClassName: $(PRODUCT_MODULE_NAME).SceneDelegate
        NSWorldSensingUsageDescription: This app needs access to world sensing to create 3D maps of your environment
        UIRequiredDeviceCapabilities:
          - arkit